# Generated by Django 6.0.5 on 2026-05-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediahub',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediahub',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
