# Generated by Django 6.0.5 on 2026-05-21 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('mediahub', '0002_mediahub_deleted_at_mediahub_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediahub',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='Category.mediacategory'),
        ),
    ]
