# Generated by Django 6.0.5 on 2026-05-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
