# Generated by Django 6.0.6 on 2026-06-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projects_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='gallery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/hero/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('launched', 'Launched'), ('maintainance', 'Maintainance')], default='planning', max_length=20),
        ),
        migrations.AddField(
            model_name='projects',
            name='tech_stack',
            field=models.TextField(blank=True, null=True),
        ),
    ]
