# Generated by Django 6.0.5 on 2026-05-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0003_mediahub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediahub',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediahub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
