# Generated by Django 6.0.5 on 2026-05-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_alter_quotation_quotation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='line_items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
