# Generated by Django 6.0.6 on 2026-06-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True),
        ),
    ]
