# Generated by Django 6.0.6 on 2026-07-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_inquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='service',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
