# Generated by Django 6.0.6 on 2026-07-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_alter_inquiry_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='questionnaire_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='questionnaire_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='questionnaire_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
