# Generated by Django 6.0.5 on 2026-05-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('lead', 'Lead'), ('churned', 'Churned')], default='lead', max_length=20),
        ),
    ]
